import control.ControlManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class AkkagenMain {

    private static final String hostname = "localhost";
    private static final int port = 9000;

    public static void main(String[] args) {

        ControlManager controlManager = new ControlManager(hostname,port);

        System.out.println("Akkagen Started");
    }
}
