package service;

import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import control.RequestManager;
import control.ServiceProviderFactory;
import datapath.DataPathManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Akkagen {

    private static volatile Akkagen akkagen;
    private final Logger log = LoggerFactory.getLogger(Akkagen.class);
    private final String hostname = "localhost";
    private final int port = 9000;
    private ActorRef dataPathManager;
    private RequestManager requestManager;
    private ServiceProviderFactory spFactory;
    private ActorSystem system;

    public Akkagen() {
    }

    public ActorRef getDataPathManager() {
        return dataPathManager;
    }

    public RequestManager getRequestManager() {
        return requestManager;
    }

    public ActorSystem getSystem() {
        return system;
    }

    public void initialize(){
        this.system = ActorSystem.create("akkagen");
        this.requestManager = new RequestManager(hostname, port, system);
        this.dataPathManager = system.actorOf(DataPathManager.props(), "datapathmanager");
        this.spFactory = new ServiceProviderFactory(this.requestManager);
    }

    public static Akkagen getInstance(){
        if(akkagen == null){
            synchronized (Akkagen.class){
                if(akkagen == null){
                    akkagen = new Akkagen();
                }
            }
        }
        return akkagen;
    }

    public static void main(String[] args) {
        Akkagen.getInstance().initialize();
        System.out.println("service.Akkagen Started");
    }
}
