package infra;

import akka.actor.ActorRef;
import akka.actor.ActorSystem;
import serviceproviders.ServiceProviderFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Akkagen {

    private static volatile Akkagen akkagen;
    private final Logger log = LoggerFactory.getLogger(Akkagen.class);
    private final String hostname = "localhost";
    private final int port = 9000;
    private ActorRef runtimeService;
    private ManagementService managementService;
    private ServiceProviderFactory spFactory;
    private ActorSystem system;

    public Akkagen() {
    }

    public void initialize(){
        this.system = ActorSystem.create("akkagen");
        this.managementService = new ManagementService(hostname, port, system);
        this.runtimeService = system.actorOf(RuntimeService.props(system), "datapathmanager");
        this.spFactory = new ServiceProviderFactory();
    }

    public static Akkagen getInstance(){
        if(akkagen == null){
            synchronized (Akkagen.class){
                if(akkagen == null){
                    akkagen = new Akkagen();
                }
            }
        }
        return akkagen;
    }

    public ActorRef getRuntimeService() {
        return runtimeService;
    }

    public ManagementService getManagementService() {
        return managementService;
    }

    public ActorSystem getSystem() {
        return system;
    }

    public ServiceProviderFactory getServiceProviderFactory() {
        return spFactory;
    }

    public static void main(String[] args) {
        Akkagen.getInstance().initialize();
        System.out.println("service.Akkagen Started");
    }
}
